import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { AuthProvider } from "@/components/AuthContext";
import styles from "@/styles/Layout.module.css"; 
import Breadcrumbs from "@/components/BreadCrumbs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <Header />
          <AuthProvider>
            <Breadcrumbs/>
            <div style={{ paddingTop: "60px" }}>
              {children}
            </div>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
